# Generated by Django 4.0.5 on 2023-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_historicaltrack'),
        ('authentication', '0006_userfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='tracks',
            field=models.ManyToManyField(default=[], related_name='favorite_tracks', to='track.track'),
        ),
    ]
