# Generated by Django 4.0.5 on 2023-01-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_historicaltrack'),
        ('authentication', '0007_alter_userfavorite_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='favorite_tracks', to='track.track'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
