# Generated by Django 4.0.5 on 2022-06-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='atrtist',
            new_name='artist',
        ),
    ]
